import React from 'react';

const Detail = () => {
    const features = [
    {
      title: 'Tailored Just for You',
      desc: 'Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here.',
    },
    {
      title: 'Learn at Your Own Pace',
      desc: 'Expand answers only when you’re ready. Dive deeper into any concept instantly with AI-powered detailed explanations.',
    },
    {
      title: 'Capture Your Insights',
      desc: 'Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful.',
    },
    {
      title: 'Understand the "Why" Behind Answers',
      desc: 'Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.',
    },
    {
      title: 'Save, Organize, and Revisit',
      desc: 'Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.',
    },
  ];
  return (
    <div className="w-full text-black -mt-15 sm:-mt-20 lg:-mt-25">

      <div className="mt-4 sm:mt-6 md:mt-10 lg:mt-12">
        <img
          src="/hero1.png"
          alt="Hero"
          width={900}
          loading='lazy'
          className="mx-auto max-w-xs sm:max-w-md md:max-w-lg lg:max-w-4xl h-auto lg:h-150 "
        />
      </div>
      <div className='bg-gradient-to-b from-[#a1a1aa] to-[#d4d4d8] p-7 mt-10 '>

            <h2 className="text-center text-2xl md:text-3xl font-semibold text-black mb-8">
        Features That Make You Shine
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
        {features.map((feature, index) => (
          <div
            key={index}
            className="bg-white rounded-xl shadow-sm p-5 border border-[#f4f4f4] hover:shadow-md transition-all duration-200"
          >
            <h3 className="text-lg font-bold mb-2 text-black">
              {feature.title}
            </h3>
            <p className="text-black">{feature.desc}</p>
          </div>
        ))}
      </div>

      </div>
      <div className='text-center bg-[#d4d4d8]  '>
        <h1>- Ashish Kumar Roy</h1>
      </div>
    </div>
  );
};

export default Detail;
